{% set name = "serialize" %}
{% set version = "0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Serialize-{{ version }}.tar.gz
  sha256: 220af8c2fde5510122dcf06edcd727f65f96a3a74645347888fef99f2f7f3f41

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5

test:
  imports:
    - serialize
    - serialize.all
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hgrecco/serialize
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A common API for multiple serialization formats with support for custom classes

  dev_url: https://github.com/hgrecco/serialize

extra:
  recipe-maintainers:
    - mikicho
